### model
model_name_or_path: Qwen/Qwen3-8B
reward_model: Skywork/Skywork-Reward-V2-Qwen3-8B
trust_remote_code: true

### method
stage: ppo
do_train: true
finetuning_type: lora
lora_rank: 8
lora_target: all
reward_model_type: full

### dataset
dataset: prism_convo
template: qwen3
cutoff_len: 2048
max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 16
dataloader_num_workers: 8  # 增加数据加载线程
packing: true  # 启用序列打包以提高训练效率

### output
output_dir: saves/qwen3-8b/lora_ppo
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true
report_to: wandb  # choices: [none, wandb, tensorboard, swanlab, mlflow]
run_name: qwen3-8b-lora-ppo-deepspeed

### acceleration & optimization
# DeepSpeed configuration
deepspeed: examples/deepspeed/ds_z2_config.json  # ZeRO-2 for better memory efficiency

# Flash Attention for faster attention computation
flash_attn: fa2  # 使用Flash Attention 2

# Gradient checkpointing to save memory
gradient_checkpointing: true

# Compilation optimization
torch_compile: true
torch_compile_backend: inductor

# Memory optimization
dataloader_pin_memory: true
dataloader_persistent_workers: true

### train
per_device_train_batch_size: 2  # 增加batch size
gradient_accumulation_steps: 4  # 相应减少accumulation steps保持总batch size
learning_rate: 1.0e-5
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

# Additional optimizations
group_by_length: true  # 按长度分组以减少padding
remove_unused_columns: true
dataloader_drop_last: true

### generate
max_new_tokens: 512
top_k: 0
top_p: 0.9
